/* =============================================================================
 * servo_main.c  --  L4 entry point.
 *
 * WHY THIS IS NOT main()
 *   platform/Core/Src/main.c is generated by CubeMX, defines main(), and calls
 *   SystemClock_Config() followed by all seventeen MX_*_Init() functions.  It
 *   owns clock and peripheral CONFIGURATION and we do not duplicate any of it.
 *
 *   It hands off with a single line inside a preserved USER CODE block:
 *
 *       /​* USER CODE BEGIN 2 *​/
 *         servo_main();
 *       /​* USER CODE END 2 *​/
 *
 *   CubeMX preserves USER CODE sections across regeneration, so that line
 *   survives.  Everything after peripheral configuration lives here, and
 *   nothing of ours lives in platform/.
 *
 * WHY CONFIGURATION ORDER DOES NOT MATTER BUT START ORDER DOES
 *   MX_TIM1_Init() configures TIM1; it never sets CEN.  So CubeMX calling it
 *   in the middle of its list is harmless.  What matters is that the carrier
 *   COUNTER starts only after every trigger consumer is armed, and that is
 *   entirely under our control below (arch section 4).
 * ============================================================================= */

#include "hal.h"
#include "foc.h"
#include "motion.h"
#include "build_config.h"
#include "contracts.h"
#include "fieldbus_app.h"
#include "param_service.h"
#include "scope_readout.h"
#include "fw_update.h"
#include <stdbool.h>

/* -----------------------------------------------------------------------------
 * Init failure.
 *
 * There is no retry and no degraded mode.  A drive that cannot arm its
 * protection tier must not turn a motor, and arch section 14 makes protection
 * stage 0 precisely so that nothing else begins until it passes.
 *
 * The brake is already engaged at this point -- it is spring-applied, so it
 * engages by default the instant power is available -- and the outputs have
 * never been enabled.  So the safe response is to stop here loudly rather
 * than to unwind anything.
 * -------------------------------------------------------------------------- */
static void init_failed(hal_trip_cause_t cause)
{
    hal_safe_state(cause);
    for (;;) {
        /* Deliberate. The independent watchdog is not being refreshed, so
         * this resets the processor within its timeout and the failure is
         * visible as a reset loop rather than as a drive that silently does
         * nothing. */
    }
}

/* -----------------------------------------------------------------------------
 * Start-up.
 *
 * The ordering constraint that shapes this whole function: the carrier is the
 * master, and when it starts it immediately begins pulsing GETSENS lines,
 * requesting DMA transfers and triggering converters.  Every one of those
 * consumers has to already exist.  So TIM1 starts LAST, inside
 * hal_init_sequencer(), after everything below it.
 * -------------------------------------------------------------------------- */
void servo_main(void)
{
    /* 1. MPU regions and caches.
     *
     * Must precede anything that places a buffer, because the non-cacheable
     * attribute on the D2 region is what keeps DMA and the core agreeing.
     * Clocks themselves were configured by SystemClock_Config() before we
     * were called. */
    if (!hal_init_memory()) {
        init_failed(HAL_TRIP_NONE);
    }

    /* 2. Persistent state, before anything depends on calibration validity.
     *
     * A failed integrity check is a fault requiring re-referencing, NOT a
     * reason to assume zero: you would otherwise report a confidently wrong
     * joint position while both encoders read perfectly (arch section 10.1). */
    (void)hal_persist_valid();

    /* 3. Safety first, literally.  STO monitors readable, brake engaged,
     *    outputs configured and OFF.  Nothing below may turn a gate on. */
    if (!hal_init_safety()) {
        init_failed(HAL_TRIP_BREAK_STO);
    }

    /* 4. Protection tier armed BEFORE the power stage can do anything.
     *    Calibration, offset measurement with the bridge off, analog
     *    watchdog limits loaded (arch section 14, stage 0). */
    if (!hal_init_adc()) {
        init_failed(HAL_TRIP_NONE);
    }

    /* 5. Encoders.  iC-MBE startup takes up to 20 ms on NERR, then
     *    configuration, then INIT to measure the line delay.  Slow, and it
     *    must complete before the sequencer starts requesting reads. */
    if (!hal_init_encoders()) {
        init_failed(HAL_TRIP_ENC_MOTOR_STATUS);
    }

    /* 6. Control state zeroed before the first ISR can run. */
    foc_init();
    motion_init();

    /* 7. Fieldbus.  Not on any deadline path, but the LAN9253 needs its
     *    39-byte SETCFG before SYNC0 means anything. */
    if (!hal_init_fieldbus()) {
        init_failed(HAL_TRIP_FIELDBUS_WATCHDOG);
    }

    /* 8. Slaves, then the carrier.  This is the one call that starts TIM1,
     *    and from the instant it returns the ISR is running every 62.5 us. */
    if (!hal_init_sequencer()) {
        init_failed(HAL_TRIP_DEADLINE);
    }

    /* -------------------------------------------------------------------
     * Main loop: whatever remains, which is most of it (arch Table 5).
     *
     * No deadline of its own.  The control ISR, the motion task and the
     * supervisory task all preempt this, so it may take as long as it likes
     * per iteration -- with one exception noted below.
     * ------------------------------------------------------------------- */
    for (;;) {
        /* EtherCAT slave stack: network state machine, mailbox, CoE.
         *
         * THE ONE RULE FOR THIS LOOP (arch section 6.1): audit every critical
         * section on this path.  An interrupt disable or raised priority mask
         * anywhere in the fieldbus stack delays the control ISR by its full
         * duration regardless of priority, and delays the fast protection
         * path with it.  That, not interrupt count, is what breaks hard
         * deadlines.  Vendor stacks contain long ones. */
        fieldbus_app_poll();

        /* Parameter service, firmware update staging, scope readout. All
         * enqueue work rather than performing transfers themselves; the
         * fieldbus peripheral has exactly one owner and it is the transfer
         * completion interrupt (arch section 9.2). */
        param_service_poll();
        scope_readout_poll();
        fw_update_poll();
    }
}