/* =============================================================================
 * fixed.c  --  the trigonometric table and its lookup.
 *
 * IMPLEMENTATION_SPEC.md section 3: around ten kilobytes in zero-wait-state
 * data memory, accurate far beyond encoder noise, and faster than the
 * hardware accelerator this part lacks would have been.
 *
 * WHY THIS TABLE IS COMPILE-TIME CONSTANT DATA, NOT GENERATED AT STARTUP:
 * generating it with sinf() at boot would pull libm into the image -- the
 * one dependency common/fixed.h's whole design exists to avoid (arch section
 * 8.1, "no float anywhere on the control path"). A compile-time table has no
 * runtime cost and no libm reference at all, so platform/STM32H743xx_FLASH.ld
 * discarding libm.a stays a real guarantee instead of an accident of what
 * happened not to get called yet.
 *
 * WHY DTCM_CONST AND NOT PLAIN const: a plain `const` table with no explicit
 * section lands in .rodata, which is FLASH -- cached and wait-stated. The
 * determinism argument (near-zero spread in the ISR duration histogram,
 * arch section 15) disappears silently: it still works, just with jitter
 * that only shows up once someone happens to look at the histogram.
 * ========================================================================== */

#include "fixed.h"
#include "hal/hal_sections.h"

/* One electrical revolution split into TRIG_TABLE_SIZE steps. sin_table[i]
 * holds sin(2*pi*i / TRIG_TABLE_SIZE) in Q15; cos is read from the same
 * table 90 degrees (TRIG_TABLE_SIZE/4 entries) ahead, so only one table is
 * stored instead of two. A full table (not a quarter-wave with folding) is
 * used deliberately: it costs 2 KB more and removes a quadrant branch from
 * the ISR (arch section 3, "raw table lookup, or linear interpolation").
 *
 * NOT hand-typed: this array is meant to be regenerated by
 * Tools/filter_design.py-style tooling from the same formula documented
 * here, not edited by hand. Until that generator exists, entry 0 is left
 * correct (sin(0) = 0) and every other slot is a placeholder computed by
 * the same rounding rule a generator would use, so the shape of the data
 * (all zero) makes the placeholder obvious rather than a wrong-looking
 * near-random table that could be mistaken for real values. */
#warning "sin table is a placeholder (all zero) -- generate it before stage 1 (IMPLEMENTATION_SPEC.md section 3); fixed_sincos() returns (0,0) for every angle until it is"
static const DTCM_CONST q15_t s_sin_table[TRIG_TABLE_SIZE] = {
    [0] = 0,
    /* PLACEHOLDER -- every other entry defaults to 0 until the table is
     * generated. See the "Traps" entry in IMPLEMENTATION_SPEC.md section 3:
     * this must be produced by tooling, not filled in by hand one value at
     * a time. */
};

#define QUARTER_TABLE (TRIG_TABLE_SIZE / 4u)

static inline q15_t sin_lookup(uint32_t idx)
{
    return s_sin_table[idx & (TRIG_TABLE_SIZE - 1u)];
}

sincos_t fixed_sincos(angle_t a)
{
    const uint32_t idx = ANGLE_TO_TRIG_IDX(a);
    sincos_t out;
    out.sin = sin_lookup(idx);
    out.cos = sin_lookup(idx + QUARTER_TABLE);
    return out;
}
