/* =============================================================================
 * fixed.c  --  the trigonometric table and the lookup.
 *
 * WHY A TABLE AT ALL
 *   This part has no CORDIC and no trigonometric accelerator, so §2 records
 *   trigonometry as "a table in data TCM".  Section 10.1 goes further: the
 *   table is faster than the hardware accelerator would have been, because a
 *   DTCM lookup is zero wait state and never cached, while an accelerator
 *   costs a write, a wait and a read.  What looked like a limitation costs
 *   nothing.
 *
 * WHY THE TABLE IS COMPILE-TIME DATA
 *   Building it with sinf() at boot would pull libm into the image, which the
 *   linker script deliberately discards so that a stray floating-point call
 *   is a LINK ERROR rather than a silent flash-resident one.  It would also
 *   put transcendental evaluation into a boot path that must finish before
 *   the carrier starts.
 *
 * WHY 1024 ENTRIES AND NOT 4096
 *   A plain lookup quantises the angle to one table step.  At 1024 entries
 *   that is 0.35 electrical degrees -- but a 19-bit encoder on a 32 pole-pair
 *   machine resolves 0.022 degrees electrical, so a plain lookup would throw
 *   away fifteen-sixteenths of the encoder's resolution and hand it back as
 *   torque ripple at the table-step rate.
 *
 *   The fix is interpolation, not a bigger table.  Linear interpolation has
 *   error h^2/8, which at h = 2*pi/1024 is 4.7e-6 -- about 0.15 LSB of Q15,
 *   comfortably below the converter's own noise.  Reaching that by brute
 *   force instead would need roughly 32768 entries, 64 KB, half of DTCM.
 *
 *   So: 2 KB and two extra multiplies, rather than 64 KB and none.  That is
 *   what "accurate far beyond encoder noise" in section 10.1 costs.
 * ============================================================================= */

#include "fixed.h"
#include "hal_sections.h"

#include "trig_table.h"      /* GENERATED by Tools/gen_trig_table.py */

_Static_assert(TRIG_TABLE_GENERATED_SIZE == TRIG_TABLE_SIZE,
               "generated table size does not match TRIG_TABLE_LOG2 in "
               "fixed.h -- regenerate with Tools/gen_trig_table.py");

#define QUARTER_TABLE   (TRIG_TABLE_SIZE / 4u)

/* Fractional bits left over after the table index is taken from the top of
 * the angle accumulator.  These are what interpolation uses; without it they
 * are simply discarded, which is the resolution loss described above. */
#define FRAC_BITS       (32u - TRIG_TABLE_LOG2)
#define FRAC_ONE        (1u << FRAC_BITS)

static inline q15_t table_at(uint32_t idx)
{
    /* The mask is the wrap.  Quarter-turn offsets for cosine, and the index
     * itself, both run past the end and come back round with no branch --
     * the same property that makes the 32-bit angle accumulator work. */
    return s_sin_table[idx & (TRIG_TABLE_SIZE - 1u)];
}

static inline q15_t interp(uint32_t idx, uint32_t frac)
{
    const int32_t a = table_at(idx);
    const int32_t b = table_at(idx + 1u);
    /* a + (b - a) * frac.  One multiply and one shift; the subtraction keeps
     * the product small enough that 32 bits is ample. */
    return (q15_t)(a + (int32_t)(((int64_t)(b - a) * (int32_t)frac) >> FRAC_BITS));
}

/* -----------------------------------------------------------------------------
 * Both values from one call.
 *
 * Returning the pair together is not a convenience.  Arch section 8.1 wants
 * the SAME sine and cosine used for the forward and the reverse transform, so
 * that coherence between them is structural rather than something a future
 * reader has to remember.  Two separate calls could silently be handed
 * different angles -- and the symptom would be a torque error that grows with
 * speed, which reads exactly like a mistuned advance term.
 * -------------------------------------------------------------------------- */
ITCM_FUNC sincos_t fixed_sincos(angle_t a)
{
    const uint32_t idx  = (uint32_t)a >> FRAC_BITS;
    const uint32_t frac = (uint32_t)a & (FRAC_ONE - 1u);

    sincos_t out;
    out.sin = interp(idx, frac);
    out.cos = interp(idx + QUARTER_TABLE, frac);
    return out;
}