#ifndef IIR_H
#define IIR_H

#include <stdint.h>

/* Biquad cascade, Direct Form II Transposed, float.  MONITORING PATHS ONLY.
 *
 * Never used inside the current loop: phase lag there costs bandwidth and
 * margin directly, and the PI integrator (foc/current_pi.h) is already a
 * low-pass. Filter the filtered-overcurrent check, the thermal accumulator,
 * the torque cross-check and the scope display freely
 * (IMPLEMENTATION_SPEC.md section 6).
 *
 * Coefficients are generated by Tools/filter_design.py into
 * config/filter_coeffs.h -- never hand-typed. */

#define IIR_CASCADE_MAX_STAGES 4u

/** @brief One biquad section's coefficients. a0 is normalised to 1. */
typedef struct {
    float b0, b1, b2;
    float a1, a2;
} iir_biquad_coeffs_t;

/** @brief One biquad section's Direct Form II Transposed state. */
typedef struct {
    float z1, z2;
} iir_biquad_state_t;

/** @brief State for a cascade of up to IIR_CASCADE_MAX_STAGES biquads. */
typedef struct {
    iir_biquad_state_t stage[IIR_CASCADE_MAX_STAGES];
} iir_cascade_state_t;

/** @brief Zero every stage's state (e.g. on re-enable, to avoid a filtered
 *         step response computed against a stale history). */
void iir_reset(iir_cascade_state_t *st);

/**
 * @brief Run one sample through a cascade of biquads.
 * @param st       Cascade state, one instance per independently-filtered signal.
 * @param coeffs   Coefficient array, config/filter_coeffs.h, length @p n_stages.
 * @param n_stages Number of biquad sections to cascade, <= IIR_CASCADE_MAX_STAGES.
 * @param in       Input sample.
 * @return         Filtered output sample.
 */
float iir_step(iir_cascade_state_t *st, const iir_biquad_coeffs_t *coeffs,
              uint32_t n_stages, float in);

#endif /* IIR_H */
