#!/usr/bin/env python3
"""
filter_design.py -- generate config/filter_coeffs.h from a design spec.

IMPLEMENTATION_SPEC.md section 4: config/filter_coeffs.h is a GENERATED file,
never hand-typed. A biquad coefficient set that looks plausible but was
transcribed with one digit wrong is exactly the kind of error that passes
review and then fails only as a subtly wrong monitoring filter -- generating
it mechanically from a checked-in design spec, plus a checksum the build
verifies, is what catches "the header was not regenerated after the design
changed" instead of trusting that to human memory.

These are MONITORING-PATH filters only (foc/iir.h): the filtered-overcurrent
check, the thermal accumulator, the torque cross-check, and the scope
display. Never the current loop -- phase lag there costs bandwidth and
margin directly.

Usage:
    filter_design.py --spec <design-spec.json> --out config/filter_coeffs.h

The design spec names each filter (overcurrent / thermal / torque_xcheck),
its cutoff(s), sample rate, and filter order; this script turns that into a
cascade of biquad sections via scipy.signal and emits them as
iir_biquad_coeffs_t initializers plus a checksum of the spec that
config/build_config.h (or the consuming .c file) can verify against
FILTER_COEFFS_CHECKSUM.

NOT YET IMPLEMENTED: no design spec format has been agreed yet (arch section
4/10 leave the cutoffs themselves as measurements still to be taken at
bring-up). This is deliberately a scaffold, not a guess at numbers that
would otherwise ship silently wrong.
"""

import hashlib
import sys
from pathlib import Path

HEADER_GUARD = "CONFIG_FILTER_COEFFS_H"


def design_biquad_cascade(cutoff_hz: float, sample_rate_hz: float, order: int):
    """Design a Butterworth low-pass as a cascade of biquad sections.

    @param cutoff_hz      -3 dB cutoff frequency, Hz.
    @param sample_rate_hz Sample rate the filter runs at, Hz.
    @param order          Filter order (2 per biquad section; must be even).
    @return               List of (b0, b1, b2, a1, a2) tuples, one per section,
                            with a0 normalised to 1.
    """
    try:
        from scipy import signal
    except ImportError as exc:
        raise SystemExit(
            "scipy is required to design filters (pip install scipy)"
        ) from exc

    if order % 2 != 0:
        raise ValueError("order must be even (one biquad per 2nd-order section)")

    sos = signal.butter(order, cutoff_hz, fs=sample_rate_hz, output="sos")
    sections = []
    for b0, b1, b2, a0, a1, a2 in sos:
        sections.append((b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0))
    return sections


def render_header(filters: dict) -> str:
    """Render config/filter_coeffs.h from a {name: [sections]} mapping.

    @param filters Mapping of filter name (e.g. "overcurrent") to its list
                    of (b0, b1, b2, a1, a2) biquad sections.
    @return         Full header text, including the checksum guard.
    """
    checksum = hashlib.sha256(repr(sorted(filters.items())).encode()).hexdigest()[:8]
    lines = [
        "/* GENERATED by Tools/filter_design.py -- do not hand-edit. */",
        f"#ifndef {HEADER_GUARD}",
        f"#define {HEADER_GUARD}",
        "",
        '#include "foc/iir.h"',
        "",
        f'#define FILTER_COEFFS_DESIGN_SPEC "{checksum}"',
        f"#define FILTER_COEFFS_CHECKSUM    0x{checksum}u",
        "",
    ]
    for name, sections in filters.items():
        macro = f"FILTER_{name.upper()}_N_STAGES"
        lines.append(f"#define {macro}   {len(sections)}u")
        lines.append(
            f"static const iir_biquad_coeffs_t FILTER_{name.upper()}_COEFFS[] = {{"
        )
        for b0, b1, b2, a1, a2 in sections:
            lines.append(
                f"    {{ {b0!r}f, {b1!r}f, {b2!r}f, {a1!r}f, {a2!r}f }},"
            )
        lines.append("};")
        lines.append("")
    lines.append(f"#endif /* {HEADER_GUARD} */")
    return "\n".join(lines) + "\n"


def main() -> int:
    """@return 2 always, until a design-spec format is agreed (see module docstring)."""
    print(__doc__, file=sys.stderr)
    print(
        "filter_design.py: no design-spec format defined yet -- nothing to generate.\n"
        "See IMPLEMENTATION_SPEC.md section 4 (config/filter_coeffs.h) and\n"
        "section 10 (Tools/).",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
