#!/usr/bin/env python3
"""
gen_trig_table.py -- emit common/trig_table.h

    python Tools/gen_trig_table.py > common/trig_table.h

WHY GENERATED AND NOT COMPUTED AT STARTUP
    Building the table with sinf() at boot pulls libm into the image, and the
    linker script deliberately discards libm.a so that a stray floating-point
    call is a link error rather than a silent flash-resident one. It would
    also put ~10 k of transcendental evaluation into a boot path that has to
    finish before the carrier starts.

WHY GENERATED AND NOT HAND-TYPED
    1024 numbers nobody will ever proofread. A transcription error produces a
    torque ripple at one specific angle, which presents as a mechanical fault.
"""
import math

N = 1024                      # must equal 1 << TRIG_TABLE_LOG2 in fixed.h
FULL = 32767                  # not 32768: +1.0 must fit in int16_t

print("/* GENERATED by Tools/gen_trig_table.py -- do not edit.")
print(" *")
print(f" * sin(2*pi*i/{N}) in Q15, {N} entries, {N*2} bytes.")
print(" * Cosine is read from the same table a quarter turn ahead, so one")
print(" * table serves both and the DTCM cost is halved.")
print(" */")
print("#ifndef COMMON_TRIG_TABLE_H")
print("#define COMMON_TRIG_TABLE_H")
print()
print(f"#define TRIG_TABLE_GENERATED_SIZE {N}u")
print()
print("static const DTCM_CONST q15_t s_sin_table[TRIG_TABLE_GENERATED_SIZE] = {")
for row in range(0, N, 8):
    vals = []
    for i in range(row, row + 8):
        v = int(round(FULL * math.sin(2.0 * math.pi * i / N)))
        v = max(-32768, min(32767, v))
        vals.append(f"{v:6d}")
    print("    " + ", ".join(vals) + ",")
print("};")
print()
print("#endif /* COMMON_TRIG_TABLE_H */")
